Fatalities listing page
cityofaustin/vision-zero pull request #1637
Opened 2024-12-20 21:55 UTC by frankhereford

## Associated issues

## Testing

**URL to test:** 

**Steps to test:**

---

#### Ship list

- [ ] Check migrations for any conflicts with latest migrations in `main` branch
- [ ] Confirm Hasura role permissions for necessary access
- [ ] Code reviewed
- [ ] Product manager approved

2024-12-20 21:56 UTC, frankhereford commented on app/components/SidebarLayout.tsx
> +                Icon={FaHeart}
I see the heart as rendered with a little tiny bit of it cut off on the right. I have toyed with this SideBarListItem component trying different utility classes to try to open it up a little more, but no dice. I'm open to any help on this one.

<img width="493" alt="image" src="https://github.com/user-attachments/assets/dfce247a-5417-4350-9b27-769b6f966f62" />

2024-12-23 15:59 UTC, johnclary commented
@frankhereford heads up that you probably want to rebase this against `john/20316-nested-object-support` ([#1634](https://github.com/cityofaustin/vision-zero/pull/1634))

2025-01-24 17:50 UTC, frankhereford commented on app/components/CrashDiagramCard.tsx
Before I rebased this to come off @johnclary's feature branch, I had merged `nextjs` into my branch, so this PR now bears some commits from upstream of John's branch. When he merges or pulls `nextjs` into his branch, this file (and others, perhaps) will drop out of this diff.

2025-01-24 17:55 UTC, frankhereford commented on app/components/CrashDiagramCard.tsx
[upstream changes](https://github.com/cityofaustin/vision-zero/pull/1637/files#r1929043913)

2025-01-24 17:55 UTC, frankhereford commented on app/components/PersonNameField.tsx
[upstream changes](https://github.com/cityofaustin/vision-zero/pull/1637/files#r1929043913)

2025-01-24 17:55 UTC, frankhereford commented on app/components/RelatedRecordTable.tsx
[upstream changes](https://github.com/cityofaustin/vision-zero/pull/1637/files#r1929043913)

2025-01-24 17:55 UTC, frankhereford commented on app/components/RelatedRecordTableRow.tsx
[upstream changes](https://github.com/cityofaustin/vision-zero/pull/1637/files#r1929043913)

2025-01-24 19:01 UTC, frankhereford commented on app/components/SidebarLayout.tsx
> +              />
[upstream changes](https://github.com/cityofaustin/vision-zero/pull/1637/files#r1929043913) for this `SideBarListItem`

2025-01-24 19:31 UTC, frankhereford commented on app/README.md
Fixed a typo and linting; this is a tagalong change

2025-01-24 19:33 UTC, frankhereford commented on app/components/CrashDiagramCard.tsx
Before I rebased this to come off @johnclary's feature branch, I had merged `nextjs` into my branch, so this PR now bears some commits from upstream of John's branch. When he merges his work or pulls `nextjs` into his branch, this file and others will drop out of this diff.

I will attempt to mark them with a file-level comment that says "upstream changes".

2025-01-24 19:34 UTC, frankhereford commented on app/components/PersonNameField.tsx
[upstream change](https://github.com/cityofaustin/vision-zero/pull/1637/files#r1929148700)

2025-01-24 19:35 UTC, frankhereford commented on app/components/RelatedRecordTable.tsx
[upstream change](https://github.com/cityofaustin/vision-zero/pull/1637/files#r1929148700)

2025-01-24 19:35 UTC, frankhereford commented on app/components/RelatedRecordTableRow.tsx
[upstream change](https://github.com/cityofaustin/vision-zero/pull/1637/files#r1929148700)

2025-01-24 19:35 UTC, frankhereford commented on app/components/SidebarLayout.tsx
> +              />
This `Create crash` sidebar item is an [upstream change](https://github.com/cityofaustin/vision-zero/pull/1637/files#r1929148700)

2025-01-24 19:36 UTC, frankhereford commented on app/components/TableWrapper.tsx
> +   * A switch that can be used to force a refetch() of the data - refetch()
tagalong typo correction; unrelated to the point of the PR

2025-01-27 16:48 UTC, chiaberry approved these changes
Test steps check out, i was able to download, sort and search. 🚢

2025-01-27 17:00 UTC, johnclary requested changes
Frank, this is looking great. and thanks for sorting out that diff!

i have requested just a few minor changes and will drop links to follow-up issues momentarily 🙏

2025-01-27 17:00 UTC, johnclary commented on app/configs/fatalitiesListViewColumns.tsx
> +  },
* https://github.com/cityofaustin/atd-data-tech/issues/20790

2025-01-27 17:05 UTC, frankhereford commented on app/configs/fatalitiesListViewTable.ts
> +const columns = fatalitiesListViewColumns.map((col) => String(col.path));
Sure enough; thanks for catching that! https://github.com/cityofaustin/vision-zero/pull/1637/commits/36238d1f8bffad8f8933b6ebec9cbbe67f75a2fc

2025-01-27 17:05 UTC, johnclary commented on app/configs/fatalitiesListViewTable.ts
> +  },
* https://github.com/cityofaustin/atd-data-tech/issues/20792

2025-01-27 17:05 UTC, frankhereford commented on app/types/fatalitiesList.ts
> +  victim_name: string;
Good catch!! Thank you, John! https://github.com/cityofaustin/vision-zero/pull/1637/commits/ed3afcc88f162b6c1197557961efe4bd6ca53627

2025-01-27 17:09 UTC, johnclary approved these changes
🚢 🚢 🚢 🚢

2025-01-27 17:13 UTC, johnclary commented
thank you, Frank!!

2025-01-27 17:13 UTC, merged